- name: Install dependencies on Fedora
  become: true
  ansible.builtin.dnf:
    name:
      - alsa-lib-devel
      - jack-audio-connection-kit-dbus
      - ladspa-devel
      - libcurl-devel
      - freetype-devel
      - fontconfig-devel
      - libX11-devel
      - libXcomposite-devel
      - libXcursor-devel
      - libXext-devel
      - libXinerama-devel
      - libXrandr-devel
      - libXrender-devel
      - webkit2gtk3-devel
      - mesa-libGLU-devel
      - mesa-libGL-devel
      - glfw-devel
      - pulseaudio-libs-devel
    state: present
