- name: Include main vars
  ansible.builtin.include_vars:
    file: vars.yml

- name: Install Neovim dependencies on Fedora
  become: true
  ansible.builtin.dnf:
    name:
      - cmake
      - gettext
      - lua
      - lua-devel
      - luarocks
      - ripgrep
    state: present

- name: Download Neovim latest release
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/latest/download/nvim-linux-arm64.tar.gz"
    dest: "/tmp/nvim-linux64.tar.gz"

- name: Remove existing Neovim directory
  ansible.builtin.file:
    path: "/opt/nvim"
    state: absent
  become: true

- name: Extract Neovim to /opt
  ansible.builtin.command: "tar -C /opt -xzf /tmp/nvim-linux64.tar.gz"
  args:
    creates: "/opt/nvim"
  become: true
