-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
-- vim.api.nvim_create_autocmd("QuickFixCmdPost", {
--     pattern = { "make" },
--     callback = function()
--         vim.cmd("copen") -- Open the quickfix list, but DO NOT jump to anything
--     end,
-- })
